- src/main/java/com/copay/app/controller/Test.java
- src/main/java/com/copay/app/dto/Test.java
- src/main/java/com/copay/app/entity/Test.java
- src/main/java/com/copay/app/exception/Test.java
- src/main/java/com/copay/app/repository/Test.java
- src/main/java/com/copay/app/service/Test.java
- src/main/java/com/copay/app/validation/Test.java
> FEAT(Structure): Added package structure.

- pom.xml
- src/main/java/com/copay/app/config/security/SecurityConfig.java
- src/main/java/com/copay/app/controller/Test.java
- src/main/java/com/copay/app/controller/TestController.java
> FEAT(Test): Added a new endpoint to test the connection between backend and frontend.

- src/main/java/com/copay/app/dto/UserRegisterRequest.java
- src/main/java/com/copay/app/service/UserService.java
> 30 implement and validate confirmpassword field in userregisterrequest with hibernate validation

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/service/ValidationService.java
> 35 implement validationservice to isolate validation logic in controller

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/service/UserService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
- src/main/java/com/copay/app/service/password/PasswordService.java
- Changed the name of AuthenticationService to AuthService.
- Changed the methods of UserService to AuthService.
- Created a new package for the password services with a class example.
Closes #40.
> REFACTOR(Structure): Optimized the structure of the project.

- src/main/java/com/copay/app/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/copay/app/config/security/SecurityConfig.java
> 56 create customauthenticationentrypoint for custom unauthorized message

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/UserController.java
- Removed all try-catch blocks and exception handling from AuthController and UserController (#51).
- Introduced UserResponseDTO to return structured JSON responses in UserController (#55).
- Updated user registration to return a formatted UserResponseDTO with relevant user details.
- Applied UserRegisterRequest DTO validation in UserController (#53).
This refactor improves code clarity, centralizes exception handling, and enhances response consistency.
Closed #51.
> REFACTOR(Controllers): Improve Exception Handling and DTO Usage

- src/main/java/com/copay/app/exception/EmailAlreadyExistsException.java
- src/main/java/com/copay/app/exception/IncorrectPasswordException.java
- src/main/java/com/copay/app/exception/PhoneAlreadyExistsException.java
- src/main/java/com/copay/app/exception/UserPermissionException.java
- src/main/java/com/copay/app/repository/UserRepository.java
- src/main/java/com/copay/app/service/UserService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
> 52 implement custom validations in authservice and userservice

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/ConnectionTestController.java
- src/main/java/com/copay/app/dto/JwtResponse.java
- src/main/java/com/copay/app/dto/UserLoginRequest.java
- src/main/java/com/copay/app/dto/UserRegisterRequest.java
- src/main/java/com/copay/app/entity/User.java
- src/main/java/com/copay/app/exception/EmailAlreadyExistsException.java
- src/main/java/com/copay/app/exception/GlobalExceptionHandler.java
- src/main/java/com/copay/app/exception/PhoneAlreadyExistsException.java
- src/main/java/com/copay/app/service/UserService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
- src/main/java/com/copay/app/validation/ValidationErrorResponse.java
> Format code according to coding standards.

- application.properties
- pom.xml
- src/main/java/com/copay/app/config/flyway/FlywayConfig.java
- src/main/java/com/copay/app/config/flyway/FlywayRunner.java
- src/main/resources/db/migration/V1__initial_schema.sql
Flyway has been successfully implemented. The initial database migration (V1__initial__schema.sql) has been set up and applied using flyway:migrate. The database schema has been created successfully with the first version of the migration, and everything is working perfectly.
Additionally, I have created a Flyway guide in the repository's discussion section to help understand the Flyway setup and usage. You can find the guide [here](https://github.com/poksyy/copay-app-backend/discussions/70).
Closes #14.
> 14 implement migration management with flyway

- pom.xml
- src/main/java/com/copay/app/config/security/SecurityConfig.java
- src/main/java/com/copay/app/controller/FakeDataController.java
- src/main/java/com/copay/app/entity/User.java
- src/main/java/com/copay/app/service/FakeDataService.java
Implemented Fake Data dependency to the project.
Documentation about the dependency [here](https://github.com/poksyy/copay-app-backend/discussions/79).
Closes #26.
> 26 fake data creation with java faker

- src/main/java/com/copay/app/CopayApplication.java
- src/main/java/com/copay/app/config/env/EnvLoader.java
- Moved the environment variable loading logic from the `CopayApplication` main class to a dedicated `EnvLoader` class.
- The `EnvLoader` class now handles the loading of the `.env` file and setting the environment variables as system properties.
- Simplified the `CopayApplication` class by calling the static `loadEnvVariables` method during application startup.
Closes #72.
> REFACTOR(main): environment variable loading logic.

- src/main/java/com/copay/app/service/UserCleanupService.java
> CHORE(UserCleanupService): Added blank space line.

- src/main/java/com/copay/app/controller/UserController.java
- src/main/java/com/copay/app/dto/user/UserCreateDTO.java
- src/main/java/com/copay/app/dto/user/UserDeleteDTO.java
- src/main/java/com/copay/app/dto/user/UserResponseDTO.java
- src/main/java/com/copay/app/dto/user/UserUpdateDTO.java
- src/main/java/com/copay/app/service/UserService.java
> 93 align usercontroller and userservice with authcontroller and authservice architecture

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/PasswordController.java
- src/main/java/com/copay/app/dto/auth/UserLoginRequest.java
- src/main/java/com/copay/app/dto/password/ForgotPasswordDTO.java
- src/main/java/com/copay/app/dto/password/ForgotPasswordResetDTO.java
- src/main/java/com/copay/app/dto/password/ForgotPasswordResetResponseDTO.java
- src/main/java/com/copay/app/dto/password/ForgotPasswordResponseDTO.java
- src/main/java/com/copay/app/dto/password/PasswordUpdateDTO.java
- src/main/java/com/copay/app/dto/password/ResetPasswordDTO.java
- src/main/java/com/copay/app/service/JwtService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
- src/main/java/com/copay/app/service/password/PasswordService.java
- src/main/resources/static/reset-password.html
> REFACTOR(Email): Changed nomeclature, generate token through email, etc.

- src/main/java/com/copay/app/dto/auth/UserRegisterStepOneDTO.java
- src/main/java/com/copay/app/dto/password/PasswordUpdateDTO.java
- src/main/java/com/copay/app/dto/password/ResetPasswordDTO.java
- src/main/java/com/copay/app/dto/user/UserUpdateDTO.java
- src/main/resources/static/reset-password.html
- Length of 8 characters
- Minimum of one capital letter
- A minimum number
Closes #37
> FIX(Password): Added new password validations.

- src/main/java/com/copay/app/service/auth/AuthService.java
> FIX(Token): Logout with the same token message fixed.

- src/main/java/com/copay/app/entity/User.java
- src/main/java/com/copay/app/service/FakeDataService.java
- src/main/java/com/copay/app/service/JwtService.java
- The new password for fake users is ‘Test12345’ referenced in the class FakeDataService.java line 30.
> FIX(Password): Added new hashed passwords.

- src/main/java/com/copay/app/controller/PasswordController.java
- src/main/java/com/copay/app/dto/responses/ResetPasswordResponseDTO.java
- src/main/java/com/copay/app/service/password/PasswordService.java
> REFACTOR(Password): Refactored code to clean up and make it more understandable.

- src/main/java/com/copay/app/service/CustomUserDetailsService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
> 119 refactor and improve login flow and error handling

- src/main/java/com/copay/app/CopayApplication.java
- src/main/java/com/copay/app/config/cors/CorsConfig.java
- src/main/java/com/copay/app/config/env/EnvLoader.java
- src/main/java/com/copay/app/config/flyway/FlywayConfig.java
- src/main/java/com/copay/app/config/flyway/FlywayRunner.java
- src/main/java/com/copay/app/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/copay/app/config/security/JwtAuthenticationFilter.java
- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/FakeDataController.java
- src/main/java/com/copay/app/controller/PasswordController.java
- src/main/java/com/copay/app/controller/UserController.java
- src/main/java/com/copay/app/dto/password/PasswordUpdateDTO.java
- src/main/java/com/copay/app/dto/password/ResetPasswordDTO.java
- src/main/java/com/copay/app/dto/user/UserUpdateDTO.java
- src/main/java/com/copay/app/entity/RevokedToken.java
- src/main/java/com/copay/app/exception/EmailAlreadyExistsException.java
- src/main/java/com/copay/app/repository/RevokedTokenRepository.java
- src/main/java/com/copay/app/service/EmailService.java
- src/main/java/com/copay/app/service/FakeDataService.java
- src/main/java/com/copay/app/service/JwtService.java
- src/main/java/com/copay/app/service/UserService.java
- src/main/java/com/copay/app/service/UserUniquenessValidator.java
- src/main/java/com/copay/app/service/ValidationService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
- src/main/java/com/copay/app/service/password/PasswordService.java
- Remove unnecessary imports.
- Rename variables so that everything has the same nomenclature.
- Token validation passes InvalidTokenException and thus fixes the duplicate entry error in the revoked token table and displays the custom token validation message.
Closes #117
> REFACTOR&FIX(QA): Refactor and code clean-up.

- src/main/java/com/copay/app/config/security/JwtAuthenticationFilter.java
> FIX(Token): Invalid token exception is send if it is null or empty.

- Copay.postman_collection.json
- src/main/java/com/copay/app/config/security/SecurityConfig.java
- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/dto/auth/CountryDialCodeDTO.java
- src/main/java/com/copay/app/service/auth/CountryCodeService.java
This reverts commit 51d99a598056e6e10a1eb846651ec20043ae4a76.
> Reapply "FEAT(Register): Added new endpoint that lists phone prefixes by country.

- src/main/java/com/copay/app/service/FakeDataService.java
- src/main/java/com/copay/app/service/GroupService.java
- src/main/java/com/copay/app/service/auth/AuthService.java
- src/main/java/com/copay/app/service/password/PasswordService.java
- src/main/java/com/copay/app/service/user/UserService.java
> FEAT(Services): Implemented @Transactional annotation to ensure that db operations are done or not done without leaving anything half done.

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
- src/main/java/com/copay/app/config/security/JwtAuthenticationFilter.java
- src/main/java/com/copay/app/exception/token/AccessRestrictedTokenException.java
- src/main/java/com/copay/app/service/JwtService.java
> 145 add register claim to temporary token and adjust jwtauthenticationfilter logic

- src/main/resources/db/migration/V10__create_expenses_table.sql
- src/main/resources/db/migration/V11__create_user_expenses_table.sql
- src/main/resources/db/migration/V12__alter_payment_confirmations.sql
- src/main/resources/db/migration/V7__rename_group_column.sql
- src/main/resources/db/migration/V9__drop_debts_expenses_tables.sql
- Drop debts and expenses tables if exists.
- Implementing users_expenses and expenses.
- Refactored id name in payment_confirmations.
- Refactored script V7 where now drops group_name instead of name.
> FEAT(Flyway): Added new sql scripts

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
- src/main/java/com/copay/app/config/security/JacksonConfig.java
> 171 implement json validation implementing jacksonconfig class to ensure only valid fields are accepted

- src/main/java/com/copay/app/service/auth/AuthServiceImpl.java
- src/main/java/com/copay/app/service/password/PasswordServiceImpl.java
- src/main/java/com/copay/app/service/user/UserAvailabilityServiceImpl.java
- src/main/java/com/copay/app/service/user/UserCleanupServiceImpl.java
- src/main/java/com/copay/app/service/user/UserServiceImpl.java
> 173 add override annotations to all implemented methods from the interface

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/GroupController.java
- src/main/java/com/copay/app/controller/UserController.java
- Removed manual validation handling in controllers.
- Centralized validation error handling in GlobalExceptionHandler.
- Automatically responds with structured error messages for validation failures.
Closes #175
> REFACTOR(Validation): Added global exception handler for validation errors

- src/main/java/com/copay/app/controller/GroupController.java
- src/main/java/com/copay/app/service/group/GroupService.java
- src/main/java/com/copay/app/service/group/GroupServiceImpl.java
> 181 validate the group creator for the update endpoints via token

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
- Handle MethodArgumentNotValidException to return detailed validation messages for invalid DTO fields.
- Handle HttpMessageNotReadableException to catch malformed or non-existent fields in JSON requests with a clear error response.
Closes #183
> FEAT(GlobalExceptionHandler): Handle DTO and JSON format errors

- src/main/java/com/copay/app/service/expense/ExpenseService.java
- src/main/java/com/copay/app/service/expense/ExpenseServiceImpl.java
- src/main/java/com/copay/app/service/expense/GroupExpenseService.java
- src/main/java/com/copay/app/service/expense/GroupExpenseServiceImpl.java
- src/main/java/com/copay/app/service/group/GroupServiceImpl.java
> 187 decouple group triggered expense logic from expenseserviceimpl into groupexpenseserviceimpl

- src/main/java/com/copay/app/controller/AuthController.java
- src/main/java/com/copay/app/controller/DatabaseController.java
- src/main/java/com/copay/app/controller/ExpenseController.java
- src/main/java/com/copay/app/controller/FakeDataController.java
- src/main/java/com/copay/app/controller/GroupController.java
- src/main/java/com/copay/app/controller/PasswordController.java
- src/main/java/com/copay/app/controller/UserController.java
- src/main/java/com/copay/app/entity/Group.java
- src/main/java/com/copay/app/service/CustomUserDetailsService.java
- src/main/java/com/copay/app/service/FakeDataService.java
- src/main/java/com/copay/app/service/auth/AuthServiceImpl.java
- src/main/java/com/copay/app/service/expense/ExpenseServiceImpl.java
- src/main/java/com/copay/app/service/expense/GroupExpenseServiceImpl.java
- src/main/java/com/copay/app/service/group/GroupService.java
- src/main/java/com/copay/app/service/group/GroupServiceImpl.java
- src/main/java/com/copay/app/service/password/PasswordService.java
- src/main/java/com/copay/app/service/password/PasswordServiceImpl.java
- src/main/java/com/copay/app/service/servicequeries/UserQueryService.java
- src/main/java/com/copay/app/service/user/UserAvailabilityService.java
- src/main/java/com/copay/app/service/user/UserAvailabilityServiceImpl.java
- src/main/java/com/copay/app/service/user/UserService.java
- src/main/java/com/copay/app/service/user/UserServiceImpl.java
- src/main/java/com/copay/app/utils/EntityValidator.java
- src/main/java/com/copay/app/validation/ValidationErrorResponse.java
- src/main/java/com/copay/app/validation/group/GroupValidator.java
- src/main/java/com/copay/app/validation/user/UserValidator.java
> 195 dto cleanup standardize annotations variable and formatting

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
- src/main/java/com/copay/app/exception/expense/DebtorNotFoundException.java
- src/main/java/com/copay/app/exception/expense/ExpenseNotFoundException.java
- src/main/java/com/copay/app/exception/group/InvalidGroupUpdateException.java
- src/main/java/com/copay/app/service/expense/GroupExpenseServiceImpl.java
- src/main/java/com/copay/app/service/group/GroupServiceImpl.java
- src/main/java/com/copay/app/service/password/PasswordServiceImpl.java
> 202 complete remaining todo task in the project related to exceptions

- src/main/java/com/copay/app/controller/ExpenseController.java
- src/main/java/com/copay/app/dto/expense/response/TotalDebtResponseDTO.java
- src/main/java/com/copay/app/dto/expense/response/TotalSpentResponseDTO.java
- src/main/java/com/copay/app/repository/expense/UserExpenseRepository.java
- src/main/java/com/copay/app/repository/paymentconfirmation/PaymentConfirmationRepository.java
- src/main/java/com/copay/app/service/expense/ExpenseService.java
- src/main/java/com/copay/app/service/expense/ExpenseServiceImpl.java
> 218 add endpoints to retrieve totalspent and totaldebt for a user in expensecontroller

- src/main/java/com/copay/app/config/GlobalExceptionHandler.java
> fix(Exception): Add exception to GlobalExceptionHandler
